# Generated by Django 4.1 on 2022-12-29 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0002_alter_contactus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={},
        ),
    ]
