# Generated by Django 4.1 on 2022-12-29 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus', '0003_alter_contactus_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
    ]
