# Generated by Django 4.1 on 2022-12-06 04:20

import ckeditor_uploader.fields
import dashboard.cms.pages.models
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('type', models.CharField(choices=[('Page', 'Page'), ('Widget', 'Widget')], default='Page', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=255, null=True, unique=True)),
                ('excerpt', models.TextField(blank=True, null=True)),
                ('comment', models.BooleanField(default=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Private', 'Private'), ('Pending', 'Pending')], default='Published', max_length=255)),
                ('visibility', models.CharField(choices=[('Pu', 'Public'), ('PP', 'Password Protected'), ('Pr', 'Private')], default='Pu', max_length=255)),
                ('feature_image', models.ImageField(default='default/default.jpg', upload_to=dashboard.cms.pages.models.user_directory_path)),
                ('publish_on', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.page')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'order_with_respect_to': 'publish_on',
            },
        ),
        migrations.CreateModel(
            name='PageSeo',
            fields=[
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='pages.page')),
                ('title', models.CharField(max_length=255, null=True)),
                ('meta_keywords', models.CharField(blank=True, max_length=500, null=True)),
                ('meta_descriptions', models.TextField(blank=True, null=True)),
                ('content_url', models.URLField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Page Seo',
                'verbose_name_plural': 'Page Seos',
            },
        ),
        migrations.CreateModel(
            name='PageMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('value', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.page')),
            ],
            options={
                'verbose_name': 'Page Meta',
                'verbose_name_plural': 'Page Metas',
            },
        ),
    ]
