# Generated by Django 4.1 on 2023-01-12 08:30

import dashboard.cms.pages.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_page_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='feature_image',
            field=models.ImageField(default='default/default.jpg', max_length=500, upload_to=dashboard.cms.pages.models.user_directory_path),
        ),
    ]
