# Generated by Django 4.1 on 2022-12-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_categories_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft'), ('Pending', 'Pending')], default='Published', max_length=255),
        ),
    ]
