# Generated by Django 4.1 on 2022-12-23 06:45

import dashboard.cms.blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='feature_image',
            field=models.ImageField(default='default/default.jpg', max_length=500, upload_to=dashboard.cms.blog.models.user_directory_path),
        ),
    ]
