# Generated by Django 4.1 on 2023-01-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurations',
            name='input_type',
            field=models.CharField(choices=[('', 'Select InputType'), ('text', 'text'), ('textarea', 'textarea'), ('file', 'file'), ('file_multiple', 'file_multiple'), ('checkbox', 'checkbox'), ('radio', 'radio'), ('button', 'button'), ('select', 'select')], default='', max_length=255),
        ),
    ]
