# Generated by Django 4.1 on 2022-12-13 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs',
        ),
    ]
